<a href="https://colab.research.google.com/github/daljeetkaursaini/Daljeetkaursaini/blob/main/pre_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



In [18]:
dataset=pd.read_csv('/content/Titanic.csv')



In [19]:
dataset




sex   age  sibsp  parch     fare embarked   class    who  alone  \
0      male  22.0      1      0   7.2500        S   Third    man  False   
1    female  38.0      1      0  71.2833        C   First  woman  False   
2    female  26.0      0      0   7.9250        S   Third  woman   True   
3    female  35.0      1      0  53.1000        S   First  woman  False   
4      male  35.0      0      0   8.0500        S   Third    man   True   
..      ...   ...    ...    ...      ...      ...     ...    ...    ...   
886    male  27.0      0      0  13.0000        S  Second    man   True   
887  female  19.0      0      0  30.0000        S   First  woman   True   
888  female   NaN      1      2  23.4500        S   Third  woman  False   
889    male  26.0      0      0  30.0000        C   First    man   True   
890    male  32.0      0      0   7.7500        Q   Third    man   True   

     survived  
0           0  
1           1  
2           1  
3           1  
4           0  
..        ...  
886         0  
887         1  
888         0  
889         1  
890         0  

[891 rows x 10 columns]

In [1]:
from sklearn import preprocessing

In [9]:
from sklearn.preprocessing import MinMaxScaler
 

In [20]:
X=dataset.iloc[:,:-2].values
y=dataset['alone'].values
print(X)
print(y[:20])


[['male' 22.0 1 ... 'S' 'Third' 'man']
 ['female' 38.0 1 ... 'C' 'First' 'woman']
 ['female' 26.0 0 ... 'S' 'Third' 'woman']
 ...
 ['female' nan 1 ... 'S' 'Third' 'woman']
 ['male' 26.0 0 ... 'C' 'First' 'man']
 ['male' 32.0 0 ... 'Q' 'Third' 'man']]
[False False  True False  True  True  True False False False False  True
  True False  True  True False  True False  True]


In [21]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
imputer=imputer.fit(X[:,1:5])
X[:,1:5]=imputer.transform(X[:,1:5])
print(X[:,1:5])


[[22.0 1.0 0.0 7.25]
 [38.0 1.0 0.0 71.2833]
 [26.0 0.0 0.0 7.925]
 ...
 [29.69911764705882 1.0 2.0 23.45]
 [26.0 0.0 0.0 30.0]
 [32.0 0.0 0.0 7.75]]


In [22]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X=LabelEncoder()
X[:,0]=labelencoder_X.fit_transform(X[:,0])
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)
print(y[:20])


[0 0 1 0 1 1 1 0 0 0 0 1 1 0 1 1 0 1 0 1]


In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=0)
print("x_train set: ",X_train.shape)
print("x_test set: ",X_test.shape)
print("y_train set: ",y_train.shape)
print("y_test set: ",y_test.shape)


x_train set:  (712, 8)
x_test set:  (179, 8)
y_train set:  (712,)
y_test set:  (179,)
